import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Stack from "@/styles/components/ui/Stack";
import TopNav from "@/styles/components/ui/TopNav";
import SideNav from "@/styles/components/ui/SideNav";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Stack direction="column" className="w-screen h-screen overflow-hidden">
          <Stack className="h-[65px] w-full bg-white border-b">
            <TopNav />
          </Stack>
          <Stack className="size-full">
            <Stack className="w-1/6 h-[calc(100vh-65px)] border-r justify-center">
              <SideNav />
            </Stack>
            <Stack className="w-5/6 p-3 overflow-auto h-[calc(100vh-65px)]">
              {children}
            </Stack>
          </Stack>
        </Stack>
      </body>
    </html>
  );
}
