import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Stack from "@/styles/components/ui/Stack";
import Box from "@/styles/components/ui/Box";
import TopNav from "@/styles/components/ui/TopNav";
import SideNav from "@/styles/components/ui/SideNav";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Stack direction="column" className="w-screen h-screen">
          <Box className="h-20 w-full fixed top-0 left-0 z-50 bg-white border-b">
            <TopNav />
          </Box>
          <Stack className="mt-20">
            <Box className="w-2/12 h-full fixed top-20 left-0 z-60 border-r">
              <SideNav />
            </Box>
            <Box className="w-10/12 ml-[17%] p-3">{children}</Box>
          </Stack>
        </Stack>
      </body>
    </html>
  );
}
